server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manual_auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update   # no Flyway; let JPA create/update schema for dev
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    problemdetails:
      enabled: true

logging:
  level:
    org.springframework.security: INFO
