spring:
  application:
    name: session-auth-mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/session_auth_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      password: password
server:
  servlet:
    session:
      cookie:
        same-site: Lax
        http-only: true
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE