spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/session_auth_db}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: Strict
spring.security.csrf.enabled: true